export const IMAGE_SELECT = 'IMAGE_SELECT';
export const IMAGE_DESELECT = 'IMAGE_DESELECT';
export const IMAGE_POPULATE = 'IMAGE_POPULATE';
export const IMAGE_ADD_TO_FAVORITE = 'IMAGE_ADD_TO_FAVORITE';

